### ISSUE TITLE
File name with \2 is gone

### ISSUE THREAD

**Issue by mkpoli** [sevenc-nanashi/pjsekai-exo#1]
![image](https://user-images.githubusercontent.com/3502597/149562422-de996561-85bc-4b21-8a5d-631fa7d1f440.png)
![image](https://user-images.githubusercontent.com/3502597/149562508-94f80757-81ba-4a63-8165-636192473df3.png)

**Comment by sevenc-nanashi** [comment]
dd644e6 で修正しました。
![image](https://user-images.githubusercontent.com/59691627/149579340-0a29c6cd-5dc0-427f-a7b2-1ba86c799d7a.png)
